[theme]
primaryColor = "#8A7B5B"
backgroundColor = "#F6F1EA"
secondaryBackgroundColor = "#FBF8F3"
textColor = "#111111"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
